### ISSUE TITLE
[Question] i can't pip install mlc-llm

### ISSUE THREAD

**Issue by bocurry** [Tao-begd/mlc-llm-android#1]
## ❓ General Questions
hello，我根据你的提示，使用”git submodule update --init --recursive“下载完成了，但是安装的时候报错了，提醒我多个顶级package。
该怎么解决呢？
我的目录以及出错的截图如下：
![image](https://github.com/Tao-begd/mlc-llm-android/assets/12912646/1ed21cb4-f139-471c-ad8a-39d84ec701c8)
![image](https://github.com/Tao-begd/mlc-llm-android/assets/12912646/7cb3b2cf-016a-4555-9640-21641612d90e)

**Comment by bocurry** [comment]
贴错图了，pip install报错的图如下：
![image](https://github.com/Tao-begd/mlc-llm-android/assets/12912646/21dd324d-94f7-4e42-8abf-7d35c02ad0bd)

**Comment by TroyTzou** [comment]
可以试试直接装mlc的whl包
`conda activate your-environment`
`python -m pip install --pre -U -f https://mlc.ai/wheels mlc-ai-nightly`
